dist: xenial
services:
- postgresql
sudo: required
addons:
  chrome: stable
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
- wget "https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz"
- tar xfz geckodriver-v0.24.0-linux64.tar.gz
- sudo mv geckodriver /usr/local/bin
- export DISPLAY=:99.0
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- wget -N http://chromedriver.storage.googleapis.com/87.0.4280.87/chromedriver_linux64.zip
  -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codacy-coverage
- pip install webdriver-manager
script:
- cd decide
- sudo apt-get install firefox
- cp travis_local_settings.py local_settings.py
- coverage run --branch --source=. ./manage.py test --keepdb
- coverage xml
- python-codacy-coverage -r coverage.xml
notifications:
  email:
    recipients:
    - antsuabon@alum.us.es
    - javnavpli@alum.us.es
    - jesgamlar@alum.us.es
    - julsoutos@alum.us.es
    - pabrodgar9@alum.us.es
    - julgomrod@alum.us.es
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  app: decide-part-andarax-auth
  strategy: git
  api_key:
    secure: NWuOn8H8UFk6aiRF2lunY+l2pI16Tn3/dbSwDvolsLzuVcwIDrupuhK5b6FaRBpV5NETSGc+CA4uigyGYwLPm6hslyNNmjY9dGQffKXsqtnVB7D+RgqrSLAxCpfg/lImVeKh0An7oyeVZL/Sysvl8ipeKLLqzc+y2/4HQP1rTBQLo32XXEOVAtoWHbKmyHllcvoGQ5+NO25m7tJwqKVwv3DwhTpgpLsuuy9G6EqLfCmSd84zB8XHcUOsle8GosCp7W+OD1KiP6f6acQy6PPoWpydRi8vMSEaAJdS84cRagRzZXyd+ugNZnNLdgt5XWUUSvcFNaNHqmSQfsQ1MIW/phJ4dSx8Ww0t6yE/fObLEL5X/HwuhBJNzuxJYaFhnm63Ew6KuA5CcINtUBVfepsnFPtGkdIIm175jrTVd3zcTPI52gYnh6UiNU0YhhLGyouM/u9KPHngP3xXA4+PmPFaAdEM6htWPpQ7GurV9Rnx1HD3esYHCK6Apk13IXj//pKfabOvxjj4o3FmgydTWfRWrGljx8ohA9n5gtm7mRrkaU4GEbkMBgWDr56GEb3ngLWScHDPo1+rhN9XZMG5Qk66btL9MppJ2jdylh6wd1q10s+73MlSFSd2kVAAx0155oOtj+aFfaxFjopmIdQ5UqW9PqCArot/sMaNV51+QQRP93E=
